// <auto-generated />
using System;
using Basic_Banking_System.DAL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Basic_Banking_System.Migrations
{
    [DbContext(typeof(DbContainer))]
    partial class DbContainerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Basic_Banking_System.DAL.Entities.Customers", b =>
                {
                    b.Property<string>("Account_Num")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Current_Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Account_Num");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Account_Num = "1258-6943-5764-12384",
                            Current_Balance = "1234$",
                            Email = "Tom@gmail.com",
                            Name = "Tom"
                        },
                        new
                        {
                            Account_Num = "4867-2134-6458-4796",
                            Current_Balance = "4590$",
                            Email = "Jena@gmail.com",
                            Name = "Jena"
                        },
                        new
                        {
                            Account_Num = "9745-1463-4795-1423",
                            Current_Balance = "487$",
                            Email = "Seray@gmail.com",
                            Name = "Seray"
                        },
                        new
                        {
                            Account_Num = "7436-1965-4567-2497",
                            Current_Balance = "500$",
                            Email = "Jerry@gmail.com",
                            Name = "Jerry"
                        },
                        new
                        {
                            Account_Num = "7894-5369-4126-7894",
                            Current_Balance = "15$",
                            Email = "Dina@gmail.com",
                            Name = "Dina"
                        },
                        new
                        {
                            Account_Num = "4897-1235-4795-6879",
                            Current_Balance = "800$",
                            Email = "Novier@gmail.com",
                            Name = "Novier"
                        },
                        new
                        {
                            Account_Num = "7842-3694-1287-9465",
                            Current_Balance = "9870$",
                            Email = "Nevya@gmail.com",
                            Name = "Nevya"
                        },
                        new
                        {
                            Account_Num = "9473-1658-4239-7458",
                            Current_Balance = "8700$",
                            Email = "Nehal@gmail.com",
                            Name = "Nehal"
                        },
                        new
                        {
                            Account_Num = "2436-8756-4123-4891",
                            Current_Balance = "6743200$",
                            Email = "Mona@gmail.com",
                            Name = "Mona"
                        },
                        new
                        {
                            Account_Num = "1297-5304-7890-1435",
                            Current_Balance = "970$",
                            Email = "Sally@gmail.com",
                            Name = "Sally"
                        },
                        new
                        {
                            Account_Num = "8402-9413-78912-1436",
                            Current_Balance = "5460$",
                            Email = "Yasin@gmail.com",
                            Name = "Yasin"
                        },
                        new
                        {
                            Account_Num = "2049-4503-7942-8576",
                            Current_Balance = "600$",
                            Email = "Ruchir@gmail.com",
                            Name = "Ruchir"
                        },
                        new
                        {
                            Account_Num = "8730-4591-2576-3971",
                            Current_Balance = "75600$",
                            Email = "Preetha@gmail.com",
                            Name = "Preetha"
                        },
                        new
                        {
                            Account_Num = "4975-2364-7941-0367",
                            Current_Balance = "400$",
                            Email = "Roy@gmail.com",
                            Name = "Roy"
                        });
                });

            modelBuilder.Entity("Basic_Banking_System.DAL.Entities.History", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senderid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("History");
                });
#pragma warning restore 612, 618
        }
    }
}
